orcasound/aifororcas-livesystem

- .github/workflows/AIForOrcas.Client.Web.yaml
- .github/workflows/AIForOrcas.Server.yaml
The `act` harness allows the default working directory to be an environment variable. Github Actions proper does not seem to.
> Fix default working-directory

- .gitignore
I personally use .venv everywhere but the longer list is taken from [here](https://github.com/github/gitignore/blob/cdd9e946da421758c6f42c427c7bc65c8326155d/Python.gitignore#L107-L114).
> chore: add Python venv names to gitignore

- ModeratorFrontEnd/AIForOrcas/AIForOrcas.Client.Web/Pages/Dashboard.razor.cs
- ModeratorFrontEnd/AIForOrcas/AIForOrcas.Client.Web/Pages/User/UserActivity.razor.cs
Change default dashboard page `filterOptions.Timeframe` to last month (`"1m"`) so that the page loads faster. The current default is `"all"` which is prohibitively large (3k+ detections).
Valid dropdown options are defined in [MetricsFilterComponent.razor](https://github.com/orcasound/aifororcas-livesystem/blob/main/ModeratorFrontEnd/AIForOrcas/AIForOrcas.Client.Web/Components/MetricsFilterComponent.razor)
I'm assuming that CD is already setup to deploy this after it's merged, else let me know what i'd need to do - thanks!
> patch dashboard/user metrics pages to improve page load time

- ModeratorFrontEnd/AIForOrcas/AIForOrcas.Client.Web/Pages/Dashboard.razor
- ModeratorFrontEnd/AIForOrcas/AIForOrcas.Client.Web/Pages/Detections/SingleDetection.razor
- ModeratorFrontEnd/AIForOrcas/AIForOrcas.Client.Web/Pages/User/UserActivity.razor
- ModeratorFrontEnd/AIForOrcas/AIForOrcas.Client.Web/Pages/_Host.cshtml
* Dashboard Tag list updated so that clicking a detection link opens a new tab so that users will not have to re-load the dashboard up close. Tab title includes the ID of the detection being viewed.
* Also added this to the User Activity/Metrics page.
> New Tab for Dashboard/User Metrics Tag Links

- InferenceSystem/README.md
- InferenceSystem/config/Production/FastAI_LiveHLS_PointRobinson.yml
- InferenceSystem/config/Production/FastAI_LiveHLS_SunsetBay.yml
- InferenceSystem/demos/hls_reader.py
- InferenceSystem/deploy-aci.yaml
- InferenceSystem/deploy/point-robinson.yaml
- InferenceSystem/deploy/sunset-bay.yaml
- InferenceSystem/requirements.txt
- InferenceSystem/src/LiveInferenceOrchestrator.py
- InferenceSystem/src/globals.py
Updated documentation 
Added two new hydrophones 
Fixed small typos
> add and activate point robinson & sunset bay hydrophones

- .github/workflows/scorecard.yml
- README.md
Start using the [OpenSSF scorecard](https://github.com/ossf/scorecard) to track overall health and security of this repository.  This PR also adds a badge to the main page to see the results, which can be clicked on to see details (which will only show results once the PR is merged causing the workflow to run for the first time).
> Enable OSSF scorecard workflow

- .github/workflows/AIForOrcas.Client.Web.yaml
- .github/workflows/AIForOrcas.Server.yaml
- .github/workflows/NotificationSystem.yaml
Turning on harden-runner in "audit" mode is the first step in hardening github workflow jobs.
For more details see https://github.com/step-security/harden-runner
> Use step-security/harden-runner in github workflows

- ModeratorFrontEnd/AIForOrcas/AIForOrcas.Client.Web/appsettings.Development.json
- ModeratorFrontEnd/AIForOrcas/AIForOrcas.Client.Web/appsettings.json
- ModeratorFrontEnd/AIForOrcas/AIForOrcas.DTO/API/Detections/DetectionQueryParameters.cs
- ModeratorFrontEnd/AIForOrcas/AIForOrcas.DTO/API/Detections/Location.cs
- ModeratorFrontEnd/OrcaHello/OrcaHello.Web.Api.Tests.Unit/Services/DetectionOrchestrationServiceTests/Default.RetrieveFilteredDetectionsAsync.cs
- ModeratorFrontEnd/OrcaHello/OrcaHello.Web.Api.Tests.Unit/Services/MetadataServiceTests/Default.RetrievePaginatedMetadataAsync.cs
- ModeratorFrontEnd/OrcaHello/OrcaHello.Web.Api/Models/Metadatas/Metadata.cs
- ModeratorFrontEnd/schema/example_v2.json
* Rename Haro Strait/Straight to Orcasound Lab
* Add additional nodes that were missing from the combobox to select from
Fixes #145
Fixes #146
This is a temporary workaround.  The correct fix is to get the full list from [live.orcasound.net/api/json/feeds](https://live.orcasound.net/api/json/feeds)
> Rename Haro Strait/Straight to Orcasound Lab

- ModelTraining/requirements.txt
Reverts orcasound/aifororcas-livesystem#165. Without torchaudio==0.6.0, model training via fastaudio v1 lib breaks
> Revert "Dev/ppastore/new lib dependencies"

- ModeratorFrontEnd/OrcaHello/OrcaHello.Web.Api.Tests.Unit/OrcaHello.Web.Api.Tests.Unit.csproj
- ModeratorFrontEnd/OrcaHello/OrcaHello.Web.Api/OrcaHello.Web.Api.csproj
- ModeratorFrontEnd/OrcaHello/OrcaHello.Web.UI.Tests.Unit/OrcaHello.Web.UI.Tests.Unit.csproj
- ModeratorFrontEnd/OrcaHello/OrcaHello.Web.UI/OrcaHello.Web.UI.csproj
.NET 7.0 is deprecated and one can no longer create App Services in Azure targeting it.
See https://devblogs.microsoft.com/dotnet/dotnet-7-end-of-support/
> Upgrade ModeratorFrontEnd to .NET 8.0 (LTS)

- ModeratorFrontEnd/OrcaHello/OrcaHello.Web.UI/Brokers/DetectionAPIBroker/DetectionAPIBroker.cs
In DetectionAPIBroker, the API was hardcoded to a local instance. This has been fixed and now correctly utilizes the AppSetting.
> Fixing a Hardcoded Local Path

- NotificationSystem/SendModeratorEmail.cs
- NotificationSystem/SendSubscriberEmail.cs
- NotificationSystem/Template/EmailTemplate.cs
> Improve Existing email template in Moderator & Subscriber

- NotificationSystem/NotificationSystem.csproj
- NotificationSystem/README.md
- NotificationSystem/SendModeratorEmail.cs
- NotificationSystem/SendSubscriberEmail.cs
- NotificationSystem/Utilities/EmailHelpers.cs
#188   Throttling to 14 email request per second implementation pending.
> Switch SendGrid Email Notification to AWS SnS

- .github/workflows/AIForOrcas.Client.Web.yaml
- .github/workflows/AIForOrcas.Server.yaml
- .github/workflows/NotificationSystem.yaml
- .github/workflows/OrcaHello.Web.Api.yaml
- .github/workflows/OrcaHello.Web.UI.yaml
Resolves 5 code scanning alerts in github
> Update github workflow permissions

- InferenceSystem/src/LiveInferenceOrchestrator.py
added an option to the config so that the models can be silent-trialed and log all predictions. Logic ensures no files are generated in production. Back-compatible with existing configs
> Ability to log classification results on local machine during testing

- InferenceSystem/README.md
- InferenceSystem/demos/hls_reader.py
- InferenceSystem/src/LiveInferenceOrchestrator.py
- InferenceSystem/src/PrepareDataForPredictionExplorer.py
- InferenceSystem/src/globals.py
- InferenceSystem/src/model/datautils.py
Eventually these should all pull from https://live.orcasound.net/api/json/feeds but the first step is to try adding the missing ones manually.
> Add missing nodes to various places in InferenceSystem

- InferenceSystem/src/model/fastai_inference.py
Addresses [https://github.com/orcasound/aifororcas-livesystem/issues/219](https://github.com/orcasound/aifororcas-livesystem/issues/219)
The number of positive calls had to be greater than the `min_num_positive_calls_threshold` to trigger a global prediction
> fixed small error in the global threshold calculation

- NotificationSystem/README.md
PR #247 upgraded NotificationSystem to .NET 8.0 but didn't update the README.md to match.
This PR updates the doc accordingly.
> Update NotificationSystem docs for .NET 8.0

- .github/dependabot.yml
Major version changes are by definition breaking changes and dependabot cannot change the things they break (e.g., the reason PR #273 failed tests). Non-major changes are backwards compatible and safe to update with dependabot.
This PR also adds the "notification system" label to any dependabot PR's against NotificationSystem code.
Leave breaking changes for issue #152
> Let dependabot skip major version changes

- NotificationSystem/NotificationSystem/SendSubscriberEmail.cs
The Azure Function for SendSubscriberEmail is failing.
This is due to a deserialization bug. SendSubscriberEmail pulls messages from a Storage Queue. We write objects into the Queue via DbToQueue Azure Function.
When putting items in the queue, we encode as base64
`await queueClient.SendMessageAsync(StringHelpers.Base64Encode(item.GetRawText()));`
When taking things out of the queue we currently deserialize without decoding back to the original JSON payload. This PR fixes the issue.
`messagesJson.Add(JsonConvert.DeserializeObject<JObject>(message.MessageText));`
See metrics/logs below:
`Exception while executing function: Functions.SendSubscriberEmail <--- Result: Failure Exception: Unexpected character encountered while parsing value: e. Path '', line 0, position 0. Stack: at …
> [BugFix] Fix deserialization bug -  SendSubscriberEmail

- NotificationSystem/NotificationSystem.sln
- NotificationSystem/NotificationSystem/Models/OrcasiteHelper.cs
- NotificationSystem/PostBackfillToOrcasite/PostBackfillToOrcasite.csproj
- NotificationSystem/PostBackfillToOrcasite/Program.cs
- NotificationSystem/README.md
PR #250 added functionality to publish _new_ detections to Orcasite, but not historical detections.
This should be done in this new standalone utility that can be manually run.
Having all detections (human and machine) in one database allows new types of historical research to be done, as discussed in Orcasite meetings.
This has been tested by posting to **beta.orcasound.net** all AI detections since July 30, 2025.  (According to Skander the beta site only has audio data newer than that so will only accept historical detections since then.)  Testing verified that:
1.  Any detections without data on beta.orcasound.net get ignored.  (Ones at the very start of the period.)
2. Newer detections get published there if not already present.
3. If already present, any duplicate detections are …
> Add a tool to copy history of detections to Orcasite

- .github/workflows/NotificationSystem.yaml
- NotificationSystem/NotificationSystem.Tests.Integration/PostToOrcasiteIntegrationTests.cs
- NotificationSystem/NotificationSystem.Tests.Unit/OrcasiteTestHelper.cs
- NotificationSystem/PostBackfillToOrcasite/Program.cs
Currently it shows up as skipped because the connection string to use is not configured, but the connection string was not in fact used for anything.
Also removed UpdateCosmosDb_WithDependencyInjection since it did the same thing as PostToOrcasite_ProcessDocumentsAsync.
After this change:
> **Passed**!  - Failed:     0, **Passed:     1**, Skipped:     0, Total:     1, Duration: 230 ms - NotificationSystem.Tests.Integration.dll (net8.0)
Fixes #286
> Enable NotificationSystem integration test to run in github CI/CD

- NotificationSystem/NotificationSystem/Models/OrcasiteHelper.cs
- NotificationSystem/NotificationSystem/NotificationSystem.csproj
- NotificationSystem/NotificationSystem/PostToOrcasite.cs
- NotificationSystem/PostBackfillToOrcasite/Program.cs
This PR does two things:
1) Updates the backfill tool to send corrected timestamps to Orcasite
2) Updates the NotificationSystem to send corrected timestamps to Orcasite for new detections.  This latter part will go away once the HLS fix in https://github.com/orcasound/orca-hls-utils/pull/24 is incorporated into the InferenceSystem so that the OrcaHello timestamps are correct to begin with.  TODO comments are in the code to remove the workaround as part of doing that step.
Addresses part of #219.  Addressing the rest of that issue requires the orca-hls-utils PR to be merged first so it can be consumed from this repository.
> Fix timestamps before posting to orcasite

- .github/dependabot.yml
- InferenceSystem/requirements.txt
Some current dependencies have problems in that InferenceSystem scripts relies on some functionality that has been removed in later versions, so requirements.txt must currently pin such dependencies to an older version, which this PR does for numpy and spacy.  Without that fix, the README instructions fail.
As noted in issue #211 there is currently no notification when there is a problem like this since there's no CI workflows for the InferenceSystem yet, and no dependabot checks.  This PR adds dependabot checks.  A separate PR will add a CI workflow.
> Let dependabot check InferenceSystem dependencies

- .github/dependabot.yml
Similar to NotificationSystem config:
* Ignore major version changes as they may be breaking changes
* Group all dependency updates into a single PR
* Add the "inference system" label on such PRs
> Update InferenceSystem dependabot config
